import { useEffect, useRef, useState } from 'react'
import type { ReactNode } from 'react'
import { Link, NavLink, Route, Routes, useLocation } from 'react-router-dom'
import { motion, MotionConfig } from 'framer-motion'
import { ArrowDown, ArrowRight, ArrowUpRight, CarFront, Check, ChevronLeft, ChevronRight, Clock3, House, Instagram, KeyRound, LockKeyhole, MapPin, Menu, MessageCircle, Microchip, Navigation, Phone, ShieldCheck, Star, Users, Wrench, X } from 'lucide-react'
import { asset, company, mapsEmbed, mapsUrl, reviewsUrl, whatsappUrl } from './config/company'
import { services } from './data/services'
import { reviews } from './data/reviews'
import { social } from './data/social'
import BrandMarquee from './components/BrandMarquee'

const external = { target: '_blank', rel: 'noopener noreferrer' }
const navigation = [{to:'/',label:'Início'},{to:'/servicos',label:'Serviços'},{to:'/sobre',label:'Sobre'},{to:'/avaliacoes',label:'Avaliações'},{to:'/contato',label:'Contato'}]
const icons = {car:CarFront,house:House,chip:Microchip,key:KeyRound,lock:LockKeyhole,repair:Wrench}
function Reveal({children,className=''}:{children:ReactNode;className?:string}) {
  return <motion.div className={className} initial={{opacity:0,y:18}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:0.08}} transition={{duration:0.5}}>{children}</motion.div>
}
function Brand() {
  const [failed,setFailed] = useState(false)
  return <Link to="/" className="brand" aria-label="Chaves Chaveiro — início">{!failed ? <img src={asset(company.images.logo)} alt="Chaves Chaveiro" onError={()=>setFailed(true)} /> : <><KeyRound aria-hidden="true"/><span><strong>CHAVES</strong><small>CHAVEIRO</small></span></>}</Link>
}
function WhatsApp({children='Chamar no WhatsApp',className=''}:{children?:ReactNode;className?:string}) {
  return <a className={`button whatsapp ${className}`} href={whatsappUrl()} {...external}><MessageCircle size={19}/>{children}<ArrowUpRight size={17}/></a>
}
function Call({short=false}:{short?:boolean}) {return <a className="button outline" href={`tel:${company.phone}`}><Phone size={18}/>{short?'Ligar':'Ligar agora'}<ArrowUpRight size={16}/></a>}
function Stars(){return <span className="stars" aria-label="5 estrelas">{Array.from({length:5},(_,i)=><Star key={i} size={15} fill="currentColor"/>)}</span>}
function Photo({path,alt,kind='service',children}:{path:string;alt:string;kind?:string;children?:ReactNode}) {
  const [failed,setFailed]=useState(false)
  return <div className={`photo photo-${kind}`}>
    {!failed ? <img src={asset(path)} alt={alt} loading={kind==='hero'?'eager':'lazy'} fetchPriority={kind==='hero'?'high':'auto'} onError={()=>setFailed(true)}/> : <div className="photo-placeholder">{kind==='hero'?<div className="key-art" aria-hidden="true"><div className="key-ring"/><div className="key-fob"><span className="fob-brand">CHAVES</span><LockKeyhole/><span className="fob-line"/><CarFront/><span className="fob-light"/></div></div>:kind==='about'?<Users size={64} strokeWidth={0.8}/>:<CarFront size={100} strokeWidth={0.7}/>}<span className="placeholder-caption">{kind==='hero'?'ESPAÇO PARA A FOTO DO MÁRCIO':kind==='about'?'ESPAÇO PARA A FOTO DO CASAL':'IMAGEM DO SERVIÇO EM BREVE'}</span></div>}
    {children}
  </div>
}
function Header(){
  const [scrolled,setScrolled]=useState(false),[open,setOpen]=useState(false)
  const location=useLocation(), toggle=useRef<HTMLButtonElement>(null)
  useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>24);onScroll();window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[])
  useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setOpen(false);toggle.current?.focus()}};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[open])
  return <header className={scrolled?'site-header scrolled':'site-header'}><div className="container header-inner"><Brand/><nav className={open?'main-nav is-open':'main-nav'} aria-label="Menu principal" id="main-nav">{navigation.map(n=><NavLink end to={n.to} key={n.to} onClick={()=>setOpen(false)} aria-current={location.pathname===n.to?'page':undefined}>{n.label}</NavLink>)}</nav><WhatsApp className="header-whatsapp">Fale no WhatsApp</WhatsApp><button ref={toggle} className="menu-toggle" aria-label={open?'Fechar menu':'Abrir menu'} aria-expanded={open} aria-controls="main-nav" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></header>
}
function Hero(){return <section className="hero hero--background" id="inicio"><div className="hero-backdrop"><Photo path={company.images.hero} alt="Márcio, proprietário do Chaves Chaveiro, segurando uma chave automotiva" kind="hero"/></div><div className="container hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="orange-line"/> CHAVEIRO EM MATOZINHOS/MG</div><h1>PERDEU A CHAVE?<br/><span>PODE CHAMAR<br/>O CHAVES.</span></h1><p className="hero-description">Soluções automotivas e residenciais em Matozinhos e região. Segurança para seguir em frente.</p><div className="hero-buttons"><WhatsApp/><Call/></div><div className="hero-rating"><span className="google-g">G</span><div><div className="rating-line"><strong>{company.googleRating.toLocaleString('pt-BR')}</strong><Stars/></div><a href={reviewsUrl} {...external}>{company.googleReviews} avaliações no Google <ArrowUpRight size={12}/></a></div><span className="rating-divider"/><div className="experience-small"><ShieldCheck size={22}/><span><strong>{company.experience}</strong><br/>de experiência</span></div></div></div><div className="hero-callout"><div className="emergency-badge"><span className="badge-icon"><Phone size={20}/></span><div><strong>Precisou? Pode chamar.</strong><span>Contato para emergências 24h</span></div><ArrowUpRight size={19}/></div></div></div><div className="container hero-bottom"><span><MapPin size={14}/> Atendimento em Matozinhos e região</span><a href="#/servicos">CONHEÇA NOSSAS SOLUÇÕES <ArrowDown size={15}/></a></div></section>}
function TrustStrip(){return <div className="trust-strip"><div className="container trust-grid">{[[ShieldCheck,'Confiança em cada atendimento'],[Microchip,'Tecnologia e experiência'],[KeyRound,'Soluções para o seu dia a dia'],[MapPin,'Perto de você, em Matozinhos']].map(([Icon,label])=>{const I=Icon as typeof ShieldCheck;return <span key={String(label)}><I size={22}/>{String(label)}</span>})}</div></div>}
function ServicesSection({full=false}:{full?:boolean}){
  const location=useLocation()
  const [filter,setFilter]=useState(new URLSearchParams(location.search).get('categoria')==='automotivo'?'automotivo':'todos')
  const shown=services.filter(s=>s.enabled && (filter==='todos'||(filter==='automotivo'?s.automotive:!s.automotive)))
  return <section className="section services-section" id="servicos"><div className="container"><Reveal className="section-heading"><div><div className="eyebrow">SOLUÇÕES QUE FACILITAM A SUA VIDA</div><h2>O QUE PODEMOS <span>RESOLVER?</span></h2><p>Soluções para seu carro, sua casa e sua segurança.</p></div>{!full&&<Link className="text-link" to="/servicos">Todos os serviços <ArrowUpRight size={19}/></Link>}</Reveal>{full&&<div className="filters" aria-label="Filtrar serviços">{[['todos','Todos os serviços'],['automotivo','Automotivos'],['residencial','Residenciais']].map(([id,label])=><button key={id} aria-pressed={filter===id} className={filter===id?'selected':''} onClick={()=>setFilter(id)}>{label}</button>)}</div>}<div className="services-grid">{shown.map((service,i)=>{const Icon=icons[service.icon];return <Reveal key={service.id}><a href={whatsappUrl(service.title)} {...external} className="service-card" aria-label={`Solicitar orçamento: ${service.title}`}><div className={`service-visual service-${service.icon}`}><Photo path={service.image} alt={service.title}/><Icon className="service-art" size={78} strokeWidth={1}/><span className="service-number">0{i+1}</span></div><div className="service-content"><div className="service-title"><h3>{service.title}</h3><ArrowUpRight size={23}/></div><p>{service.description}</p><span className="service-cta">SOLICITAR ORÇAMENTO <ArrowRight size={14}/></span></div></a></Reveal>})}</div>{full&&<p className="service-note">Conte o que você precisa. Nossa equipe confirma a disponibilidade e orienta sobre a melhor solução.</p>}</div></section>
}
function Automotive(){return <section className="automotive"><div className="automotive-art"><Photo path={company.images.automotive} alt="Fotografia automotiva da empresa" kind="automotive"/></div><div className="container"><Reveal className="automotive-copy"><div className="eyebrow">ESPECIALIDADE QUE FAZ A DIFERENÇA</div><h2>SEU CARRO NA MÃO<br/>DE QUEM <span>ENTENDE.</span></h2><p>Experiência, tecnologia e cuidado com o que leva você mais longe. Fale com quem entende da sua necessidade.</p><Link to="/servicos?categoria=automotivo" className="button orange">Ver soluções automotivas <ArrowUpRight size={18}/></Link></Reveal></div></section>}
function About(){return <section className="section about-section" id="sobre"><div className="container about-grid"><Reveal className="about-photo"><Photo path={company.images.about} alt="Casal responsável pelo Chaves Chaveiro" kind="about"/><div className="about-stamp"><KeyRound size={29}/><span>GENTE DE VERDADE.<br/><strong>CONFIANÇA DE PERTO.</strong></span></div></Reveal><Reveal className="about-copy"><div className="eyebrow">NOSSA HISTÓRIA, A SUA CONFIANÇA</div><h2>QUASE 10 ANOS<br/><span>ABRINDO CAMINHOS.</span></h2><p>O Chaves Chaveiro atende Matozinhos e região com soluções automotivas e residenciais, combinando experiência, tecnologia e um atendimento próximo de cada cliente.</p><p>Conduzido pelo casal, o negócio vem construindo sua reputação ao longo de quase 10 anos com agilidade, confiança e qualidade no atendimento. Aqui, cada cliente é recebido com atenção.</p><div className="about-stats"><div><strong>QUASE 10</strong><span>anos de experiência</span></div><div><strong>4,9 <Star size={18} fill="currentColor"/></strong><span>no Google · 200 avaliações</span></div></div><span className="local-note"><MapPin size={17}/> Atendimento em Matozinhos e região.</span></Reveal></div></section>}
function Reviews(){
  const track=useRef<HTMLDivElement>(null)
  return <section className="section reviews-section" id="avaliacoes"><div className="container"><Reveal className="reviews-heading"><div className="eyebrow">QUEM CONHECE, CONFIA</div><h2>QUEM CHAMA O CHAVES <span>RECOMENDA.</span></h2><div className="review-summary"><strong>4,9</strong><Stars/><span>200 avaliações no Google</span></div></Reveal><div className="reviews-grid" ref={track} tabIndex={0} role="region" aria-label="Avaliações de clientes; deslize para ver mais">{reviews.map(r=><article className="review-card" key={r.name}><div className="flex items-center justify-between"><Stars/><span className="google-g">G</span></div><blockquote>“{r.text}”</blockquote><div className="review-person"><span className="avatar">{r.name.split(' ').slice(0,2).map(n=>n[0]).join('')}</span><div><strong>{r.name}</strong><span>Avaliação no Google</span></div><Check size={15}/></div></article>)}</div><div className="review-controls"><button aria-label="Avaliação anterior" onClick={()=>track.current?.scrollBy({left:-320,behavior:'smooth'})}><ChevronLeft/></button><button aria-label="Próxima avaliação" onClick={()=>track.current?.scrollBy({left:320,behavior:'smooth'})}><ChevronRight/></button></div><a href={reviewsUrl} className="text-link review-link" {...external}>Ver avaliações no Google <ArrowUpRight size={17}/></a></div></section>
}
function Emergency(){return <section className="emergency-section"><div className="container emergency-inner"><div><div className="eyebrow">CONTE COM A GENTE</div><h2>PRECISOU? <span>PODE CHAMAR O CHAVES.</span></h2><p>Em caso de urgência, entre em contato pelo WhatsApp ou telefone a qualquer hora.</p></div><div className="emergency-actions"><WhatsApp>Falar no WhatsApp</WhatsApp><Call/></div></div></section>}
function Contact(){return <section className="section contact-section" id="contato"><div className="container"><div className="section-heading"><div><div className="eyebrow">PERTINHO DE VOCÊ</div><h2>ONDE <span>ESTAMOS.</span></h2></div><span className="text-muted">Matozinhos, Minas Gerais</span></div><div className="contact-grid"><div className="contact-info"><h3>CHAVES CHAVEIRO</h3><div className="contact-item"><MapPin/><div><strong>Venha nos visitar</strong><p>{company.address.street}<br/>{company.address.neighborhood} · {company.city} - {company.state}<br/>CEP {company.address.zipCode}</p></div></div><div className="contact-item"><Phone/><div><strong>Telefone e WhatsApp</strong><a href={`tel:${company.phone}`}>{company.phoneDisplay}</a><a className="contact-wa" href={whatsappUrl()} {...external}>Conversar no WhatsApp <ArrowUpRight size={13}/></a></div></div><div className="contact-item"><Clock3/><div><strong>Horário de funcionamento</strong><p>Atendimento comercial até {company.businessClosingTime.replace(':','h')}.<br/><span className="orange-text">Urgências: entre em contato a qualquer hora.</span></p></div></div><a className="button orange" href={mapsUrl} {...external}><Navigation size={17}/> Traçar rota <ArrowUpRight size={18}/></a></div><div className="map-wrap"><iframe title="Localização do Chaves Chaveiro em Matozinhos" src={mapsEmbed} loading="lazy" referrerPolicy="no-referrer-when-downgrade" allowFullScreen/><a className="map-link" href={mapsUrl} {...external}><MapPin size={17}/> Abrir no Google Maps <ArrowUpRight size={15}/></a></div></div></div></section>}
function Footer(){return <><footer><div className="container footer-main"><div><Brand/><p>Segurança, agilidade e confiança<br/>em cada atendimento.</p></div><div className="footer-links"><strong>EXPLORE</strong>{navigation.map(n=><Link key={n.to} to={n.to}>{n.label}</Link>)}</div><div className="footer-contact"><strong>PODE CHAMAR O CHAVES</strong><a href={`tel:${company.phone}`}>{company.phoneDisplay}</a>{social.map(s=><a key={s.label} href={s.url} {...external}><Instagram size={16}/>{s.handle}</a>)}<span>Matozinhos/MG</span></div><div className="footer-signature"><KeyRound size={29}/><span>ABRINDO CAMINHOS.<br/><strong>CONECTANDO CONFIANÇA.</strong></span></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Chaves Chaveiro. Todos os direitos reservados.</span><span>Feito para você seguir em frente. <ArrowUpRight size={13}/></span></div></footer><div className="mobile-cta"><a href={`tel:${company.phone}`}><Phone/>Ligar</a><a href={whatsappUrl()} className="mobile-whatsapp" {...external}><MessageCircle/>WhatsApp</a><a href={mapsUrl} {...external}><Navigation/>Rotas</a></div></>}
function Page({children,label}:{children:ReactNode;label:string}){return <div className="inner-page"><div className="container breadcrumb"><Link to="/">Início</Link><ChevronRight size={14}/><span>{label}</span></div>{children}</div>}
function ServicePage(){const location=useLocation();return <Page label="Serviços"><ServicesSection full key={location.search}/><Emergency/></Page>}
function RouteEffects(){const {pathname}=useLocation();useEffect(()=>{window.scrollTo({top:0,behavior:'instant'});const page=navigation.find(n=>n.to===pathname)?.label;document.title=pathname==='/'?'Chaves Chaveiro | Chaveiro em Matozinhos MG':`${page||'Página não encontrada'} | Chaves Chaveiro`;document.getElementById('main-content')?.focus({preventScroll:true})},[pathname]);return null}
export default function App(){return <MotionConfig reducedMotion="user"><a className="skip-link" href="#main-content" onClick={e=>{e.preventDefault();document.getElementById('main-content')?.focus()}}>Pular para o conteúdo</a><RouteEffects/><Header/><main id="main-content" tabIndex={-1}><Routes><Route path="/" element={<><Hero/><TrustStrip/><ServicesSection/><BrandMarquee/><Automotive/><About/><Reviews/><Emergency/><Contact/></>}/><Route path="/servicos" element={<ServicePage/>}/><Route path="/sobre" element={<Page label="Sobre"><About/><TrustStrip/><Reviews/><Emergency/></Page>}/><Route path="/avaliacoes" element={<Page label="Avaliações"><Reviews/><Emergency/></Page>}/><Route path="/contato" element={<Page label="Contato"><Contact/><Emergency/></Page>}/><Route path="*" element={<Page label="Página não encontrada"><section className="container section"><h1>PÁGINA NÃO ENCONTRADA.</h1><p>Vamos encontrar o caminho de volta.</p><Link className="button orange" to="/">Voltar ao início <ArrowRight size={18}/></Link></section></Page>}/></Routes></main><Footer/></MotionConfig>}
